dist: trusty
sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libsdl2-2.0-0 libsdl2-dev
script:
  - cargo build --all
  - cargo test --all --features=tests