[package]
authors = ["Matthew Collins <me@thinkof.name>"]
name = "fungui"
version = "0.1.0"

[dependencies]
fnv = "1.0.6"
ref_filter_map = "1.0.1"
bitflags = "1.0.4"

[dependencies.fungui_syntax]
path = "./syntax"

[workspace]
members = [
    "./syntax"
]

[features]
tests = []